debugMode: true
adaptor:
  host: example.com
  port: 6789
metadataKeys:
  - traffic-profile
serviceRegistry:
  gcpServiceDirectory:
    pollInterval: 18
    region: us-west1
    projectID: my-project
    serviceAccountPath: /path/to/the/service-account.json

